// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dsc.cinephile.domain;

import br.ufpb.dsc.cinephile.domain.Category;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Category_Roo_Configurable {
    
    declare @type: Category: @Configurable;
    
}
